Цели и задачи
Duckest/Duckest pull request #6
Opened 2021-03-09 18:12 UTC by AnnaNebuko

Глава первая нашей курсовой работы

2021-03-09 18:17 UTC, AnnaNebuko commented
Наши грандиозные цели и важные задачи

2021-03-19 14:53 UTC, GlebKirsan requested changes
Перенести в README.md, чтобы эти сведения отображались на странице документов в репозитории, сам файл "Общие сведения.docx" можно удалить

2021-03-22 09:48 UTC, GlebKirsan requested changes
Пункты 1.1 и 1.2 всё ещё отображаются слипшимися. Для разбиения на разные строки в mardown-файлах нужно делать по пустой строке между этими строками.

2021-03-26 15:08 UTC, GlebKirsan requested changes
Краткое описание превратилось в окно со слайдером. 
Главные пункты можно сделать заголовками для улучшения читаемости

2021-03-26 15:30 UTC, GlebKirsan approved these changes

2021-03-26 15:30 UTC, merged